#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=SimpleErwin
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=simple_erwin.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Activate your environment
# source activate erwin
source erwin/bin/activate
# Check whether the GPU is available
export WANDB_API_KEY=72b9aaecbf5c166c940ca899cfdf325d72b22b65
# export WANDB_MODE=disabled
srun python simple_erwin_init.py
